public_html/main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = "main"

urlpatterns = [
    path("", views.index, name="home"),
    path('about', views.about, name="about"),
    path('basket', views.basket, name="basket"),
    path('comments', views.comments, name="comments"),
    path('news', views.news, name="news"),
    path('<int:pk>', views.NewDetailView.as_view(), name="newprod"),
    path('new<int:pk>', views.NewNewView.as_view(), name="newnew"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

public_html/testsite/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

public_html/main/models.py
from django.db import models


class Catalog(models.Model):
    name = models.CharField("имя товара", max_length=50)
    price = models.IntegerField("цена товара")
    sizes = models.TextField("размеры", max_length=150)
    deskription = models.TextField("описание товара ( для отдельной страницы )", blank=True)
    photo = models.ImageField("фотография товара ( для каталога )", upload_to='media/prod_images')
    miniphoto1 = models.ImageField("1 фотография товара ( для отдельной страницы )", upload_to='media/prod_images', blank=True)
    miniphoto2 = models.ImageField("2 фотография товара ( для отдельной страницы )", upload_to='media/prod_images', blank=True)
    miniphoto3 = models.ImageField("3 фотография товара ( для отдельной страницы )", upload_to='media/prod_images', blank=True)
    miniphoto4 = models.ImageField("4 фотография товара ( для отдельной страницы )", upload_to='media/prod_images', blank=True)
    category = models.CharField("категория товара", max_length=50)
    brand = models.CharField('Бренд товара', max_length=50)


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
      
      
      
        
        
        
class Comments(models.Model):
    username = models.CharField('имя пользователя', max_length=40)
    comment_text = models.TextField('текст отзыва', max_length=150)
    score = models.IntegerField("оценка")

    def __str__(self):
        return self.comment_text


    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"


        
    

class News(models.Model):
    header = models.CharField('Заголовок', max_length=70)
    news_text = models.TextField('текст новости')
    photo = models.ImageField("картинка для новости", upload_to="media/prod_images", blank=True)
    

    def __str__(self):
        return self.header
    
    
    class Meta:
        verbose_name = "Новость"
        verbose_name_plural = "Новости"

public_html/main/forms.py
from .models import Comments
from django.forms import ModelForm, TextInput, EmailInput, Textarea, IntegerField, NumberInput




class CommentForm(ModelForm):
    class Meta:
        model = Comments
        fields = ['username', 'comment_text', "score"]

        widgets = {
            'username': TextInput(attrs={
                'class': 'input_name',
                'placeholder': "Ваше имя"
            }),

            'comment_text': Textarea(attrs={
                'class': 'input_text',
                'placeholder': "Отзыв"
            }),

            'score': NumberInput(attrs={
                'class': 'score_input',

            }),



        }

public_html/main/views.py
import time
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import CommentForm
from .models import Catalog, Comments, News
from django import forms
from django.views.generic import DetailView
import urllib.parse
from PIL import Image
import os


cart = 1
is_auth = 0
login = ''
corrdate = []






class NewDetailView(DetailView):
    model = Catalog
    template_name = 'main/details_view.html'
    context_object_name = 'product'

class NewNewView(DetailView):
    model = News
    template_name = 'main/new_view.html'
    context_object_name = 'new'


def index(request):
    
    brands = []
    categories = []

    prod = Catalog.objects.all()
    # brands = Brands.objects.all()
    sq = request.GET.get('search')
    
    
    for item in prod:
        if item.brand not in brands:
            brands.append(item.brand)
    
    
    
    for item in prod:
        if item.category not in categories:
            categories.append(item.category)
    
    
    if sq:
        pass
    else:
        sq = None
    print(sq)
    global is_auth
    data = {
        'prod': prod,
        "search_query": sq,
        "is_auth" : is_auth,
        "brands": brands,
        "categories": categories,
    }
    return render(request, "main/mainpage.html", data)

def about(request):
    global is_auth
    data = {
        "is_auth": is_auth
    }
    return render(request, "main/about.html", data)





def basket(request):

    encode = request.COOKIES.get('basket')
    
    try:
        basket = urllib.parse.unquote(encode)
    except: basket = 0

    if basket == ",":
        basket = ''



    if basket:
        basket = urllib.parse.unquote(encode)
        basket = basket.split(',')
        basket.pop()
        print(basket, " корзина")

        catalog = Catalog.objects.all()

        products = []


        for item in basket:
            try:
                products.append(catalog.get(pk=item))
            except Exception: pass



        if products:
            sost = 1

        else: sost = 0


        data = {
            "basket": basket,
            "catalog": products,
            "sost": sost
        }

        return render(request, "main/basket.html", data)

    else:
        data = {
            "sost": 0
        }
        return render(request, "main/basket.html", data)


def comments(request):
    is_comm = 0

    comments = Comments.objects.all()
    form = CommentForm()


    encode = request.COOKIES.get('secret_key_comm')
    try:
        is_comm = urllib.parse.unquote(encode)
    except Exception:
        pass


    print(is_comm)
    if is_comm == "121912":
        data = {
            "comments": comments,
            "form": form,
            'is_comm': 1
        }

        return render(request, "main/comments.html", data)

    else:
        if request.method == "POST":
            form = CommentForm(request.POST)
            if form.is_valid():
                form.save()
                response = redirect('/')
                response.set_cookie("secret_key_comm", '121912', max_age=86400,)
                return response
            else:
                pass




        data = {
            "comments": comments,
            "form": form,
            "is_comm:": 2
        }
        return render(request, "main/comments.html", data)
        
        

def news(request):
    news = News.objects.all()
    data = {
            'news': news,
        }
    return render(request, "main/news.html", data)

public_html/main/templates/main/about.html
{% extends 'main/example.html' %}
{% load static %}
{% block content %}
    <title>Информация о нас</title>
    <script src="{% static '/main/js/about.js' %}"></script>
    <link rel="stylesheet" href="{% static 'main/css/about.css' %}">


    <div id="all_content">


        <div class="block" id="first_block">
            <img class="img_block" src="{% static 'main/img/about/block1.png' %}">
            <span class="text">У нас вы можете купить оригинальные вещи <br> по самым оптимальным ценам на рынке.</span>
        </div>

        <hr class="hor_line">

        <div class="block" id="second_block">
            <img class="img_block" src="{% static 'main/img/about/block2.png' %}">
            <span class="text" >Мы доставляем вещи по всей России!</span>
        </div>

        <hr class="hor_line">

        <div class="block" id="third_block">
            <img id="img_block3" src="{% static 'main/img/about/block3.png' %}">
            <span>Так же мы предоставляем услуги логистической компании и доставляем товары с Европы и Китая включительно!</span>
        </div>

        <hr class="hor_line">

        <div class="block" id="four_block">
            <img id="img_block4" src="{% static 'main/img/about/block4.png' %}">
            <span>Друзья, <br>
            если вы не нашли вещь, которую хотели бы приобрести то мы готовы выслушать ваши предложения и постараться найти то,
            что вам нужно.

            Мы всегда открыты для обратной связи и готовы сделать все возможное,
            чтобы удовлетворить потребности наших клиентов.
           </span>
        </div>

        <hr class="hor_line">

        <div class="block" id="five_block">
            <img id="img_block5" src="{% static 'main/img/about/block5.png' %}">
            <span>Связаться с нами вы можете в нашей группе Вконтакте или Телеграм канале</span>
            <button id="vk_btn"><img id="vklogo" src="{% static '/main/img/vk_logo.png' %}" alt="1">BLYNSKY SHOP</button>

            <button id="tg_btn"><img id="tglogo" src="{% static '/main/img/tglogo.png' %}" alt="1">@BLYNSKYSHOP</button>
        </div>

    </div>
{% endblock %}

public_html/main/templates/main/basket.html
{% extends 'main/example.html' %}
{% load static %}
{% block content %}

    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="{% static '/main/js/scripts.js' %}"></script>
    <script src="{% static '/main/js/basket.js' %}"></script>
    <link rel="stylesheet" href="{% static 'main/css/basket.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/order.css' %}">
    <title>Корзина</title>



    <div id="hidden_order">
        <div class="order">
            <button id="close"><img id="close_img" src="{% static '/main/img/close.svg' %}" alt=""></button>
            <h3>Оформление заказа</h3>
            <hr>
            <h1 id="text_info">Оформить заказ вы можете в личных сообщениях нашей группы ВКонтакте</h1>
            <button id="vk_btn"><img id="vklogo" src="{% static '/main/img/vk_logo.png' %}" alt="1">BLYNSKY SHOP</button>
            <br>
            <button id="tg_btn"><img id="tglogo" src="{% static '/main/img/tglogo.png' %}" alt="1">@BLYNSKYSHOP</button>
        </div>
    </div>

    <body id="body">




        {% if sost == 0 %}
            <h1>Ваша корзина пуста :(</h1>
        {% endif %}

        {% if sost == 1 %}

            <h2>Ваша корзина</h2>

            <div class="div_basket">
                {% for el in catalog %}
                    <div class="div_prod">

                        <div class="info">
                            <div id="img_div">
                                <img class="img" src="{{ el.photo.url }}">
                            </div>

                            <div id="name_and_size_div">
                                <h4 class="name">{{ el.name }}</h4>
                                <h6 class="sizes">Доступные размеры: <br> {{ el.sizes }}</h6>
                            </div>
                        </div>

                        <div class="div_price"><h4 class="price">{{ el.price }} ₽</h4></div>
                        <div class="div_buttons">
                            <button class="btn btn-success del" id="btndel" data-button-id='{{ el.id }}'>Удалить</button>
                            <button id="order_btn" class="btn btn-success ord">Оформить заказ</button>

                        </div>


                    </div>
                {% endfor %}
            </div>


        {% endif %}

    </body>


{% endblock %}

public_html/main/templates/main/comments.html
{% extends 'main/example.html' %}
{% load static %}
{% block content %}
    <title>Отзывы</title>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<!--    <script src="{% static '/main/js/scripts.js' %}"></script>-->
    <link rel="stylesheet" href="{% static 'main/css/comments.css' %}">
    <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.js"></script>
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
    <script src="{% static '/main/js/comments.js' %}"></script>

    


	<div id="body">
        <h1>Отзывы</h1>
        <button id="add_comment"><img id="img_add_comment" src="{% static 'main/img/comments/plus.png' %}" alt=""> Добавить отзыв</button>

        <div id="form_div">
            <form method="post" id="form_comment">
                <button id="close" type="button"><img id="close_img" src="{% static '/main/img/close.svg' %}" alt=""></button>
                <h3>Оставить отзыв</h3>
                {% csrf_token %}
                {{ form.username }}<br>
                {{ form.comment_text }}<br>
                {{ form.score }}<br>

                <div id="score_div">
                    <h3>Оценка:</h3><br>
                    <div id="score_btns_div">
                        <button type="button" id="score_pos_btn"><img class="img_score" src="{% static 'main/img/comments/pos.png' %}" alt=""></button>
                        <button type="button" id="score_neg_btn"><img class="img_score" src="{% static 'main/img/comments/neg.png' %}" alt=""></button>
                    </div>
                </div>

                {% if is_comm == 1 %}
                    <button class="post_comment_btn" id="error_btn" type="button">Недоступно</button>
                    <br>
                    <span>вы сегодня уже оставляли отзыв на нашем сайте</span>
                {% else %}
                    <button class="post_comment_btn" type="submit">Оставить отзыв</button>
                {% endif %}
            </form>
        </div>

        <div class="all_comments">

            {% for elem in comments %}
            <div class="comment_div">
                <div class="user_img_div">
                    <img class="user_img" src="{% static 'main/img/comments/user_logo.svg' %}" alt="">
                </div>
                <div class="user_name_and_text">
                    <div class="name_and_score">
                        <h5 class="name_user">{{ elem.username }}</h5>
                        {% if elem.score == 1 %}
                            <img class="img_score_comment" src="{% static 'main/img/comments/pos.png' %}" alt="">
                        {% endif %}

                        {% if elem.score == 2 %}
                            <img class="img_score_comment" src="{% static 'main/img/comments/neg.png' %}" alt="">
                        {% endif %}


                    </div>

                    <h5 class="comment_text">{{ elem.comment_text }}</h5>
                </div>

            </div>
            {% endfor %}
        </div>


	</div>




{% endblock %}

public_html/main/templates/main/details_view.html
{% extends 'main/example.html' %}
{% load static %}
{% block content %}
    <title>{{ product.name }}</title>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="{% static '/main/js/scripts.js' %}"></script>
    <link rel="stylesheet" href="{% static 'main/css/detail.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/order.css' %}">

    
	<body id="body">

		<div id="detdiv" class="detail_div">

			<div id="hidden_order">
				<div class="order">
					<button id="close"><img id="close_img" src="{% static '/main/img/close.svg' %}" alt=""></button>
					<h3>Оформление заказа</h3>
					<hr>
					<h1 id="text_info">Оформить заказ вы можете в личных сообщениях нашей группы ВКонтакте</h1>
					<button id="vk_btn"><img id="vklogo" src="{% static '/main/img/vk_logo.png' %}" alt="1">BLYNSKY SHOP</button>
					<br>
					<button id="tg_btn"><img id="tglogo" src="{% static '/main/img/tglogo.png' %}" alt="1">@BLYNSKYSHOP</button>

				</div>
			</div>



			{% if product.miniphoto1 == "" %}

				<div class="all">
				    <input checked type="radio" name="respond" id="desktop">
					<article id="slider">
							<input checked type="radio" name="slider" id="switch1">
							<input type="radio" name="slider" id="switch2">
							<input type="radio" name="slider" id="switch3">
							<input type="radio" name="slider" id="switch4">
							<input type="radio" name="slider" id="switch5">
						<div id="slides">
							<div id="overflow">
								<div class="image">
									<article><img class="prod_img" src="{{ product.photo }}"></article>
								</div>
							</div>
						</div>


					</article>
				</div>
				<hr class="personal_hr">
			{% elif product.miniphoto2 == "" %}
             
				<div class="all">
				    <input checked type="radio" name="respond" id="desktop">
					<article id="slider">
							<input checked type="radio" name="slider" id="switch1">
							<input type="radio" name="slider" id="switch2">
							<input type="radio" name="slider" id="switch3">
							<input type="radio" name="slider" id="switch4">
							<input type="radio" name="slider" id="switch5">
						<div id="slides">
							<div id="overflow">
								<div class="image">
									<article><img class="prod_img" src="{{ product.photo }}"></article>
									<article><img class="prod_img" src="{{ product.miniphoto1 }}"></article>
								</div>
							</div>
						</div>

						<div id="controls">
							<label for="switch1"></label>
							<label for="switch2"></label>
						</div>

						<div id="active">
							<label for="switch1"></label>
							<label for="switch2"></label>

						</div>
					</article>
				</div>
				<hr>

			{% elif product.miniphoto3 == "" %}
			   
				<div class="all">
				    <input checked type="radio" name="respond" id="desktop">
					<article id="slider">
							<input checked type="radio" name="slider" id="switch1">
							<input type="radio" name="slider" id="switch2">
							<input type="radio" name="slider" id="switch3">
							<input type="radio" name="slider" id="switch4">
							<input type="radio" name="slider" id="switch5">
						<div id="slides">
							<div id="overflow">
								<div class="image">
									<article><img class="prod_img" src="{{ product.photo }}"></article>
									<article><img class="prod_img" src="{{ product.miniphoto1 }}"></article>
									<article><img class="prod_img" src="{{ product.miniphoto2 }}"></article>

								</div>
							</div>
						</div>
						<div id="controls">
							<label for="switch1"></label>
							<label for="switch2"></label>
							<label for="switch3"></label>

						</div>
						<div id="active">
							<label for="switch1"></label>
							<label for="switch2"></label>
							<label for="switch3"></label>

						</div>
					</article>
				</div>
				<hr>
				
			{% elif product.miniphoto4 == "" %}
           
			<div class="all">
			    <input checked type="radio" name="respond" id="desktop">
				<article id="slider">
						<input checked type="radio" name="slider" id="switch1">
						<input type="radio" name="slider" id="switch2">
						<input type="radio" name="slider" id="switch3">
						<input type="radio" name="slider" id="switch4">
						<input type="radio" name="slider" id="switch5">
					<div id="slides">
						<div id="overflow">
							<div class="image">
								<article><img class="prod_img" src="{{ product.photo }}"></article>
								<article><img class="prod_img" src="{{ product.miniphoto1 }}"></article>
								<article><img class="prod_img" src="{{ product.miniphoto2 }}"></article>
								<article><img class="prod_img" src="{{ product.miniphoto3 }}"></article>

							</div>
						</div>
					</div>
					<div id="controls">
						<label for="switch1"></label>
						<label for="switch2"></label>
						<label for="switch3"></label>
						<label for="switch4"></label>

					</div>
					<div id="active">
						<label for="switch1"></label>
						<label for="switch2"></label>
						<label for="switch3"></label>
						<label for="switch4"></label>

					</div>
				</article>
			</div>
			<hr>	
			
			
			{% elif product.miniphoto4 %}
            
			<div class="all">
			    <input checked type="radio" name="respond" id="desktop">
				<article id="slider">
						<input checked type="radio" name="slider" id="switch1">
						<input type="radio" name="slider" id="switch2">
						<input type="radio" name="slider" id="switch3">
						<input type="radio" name="slider" id="switch4">
						<input type="radio" name="slider" id="switch5">
					<div id="slides">
						<div id="overflow">
							<div class="image">
								<article><img class="prod_img" src="{{ product.photo }}"></article>
								<article><img class="prod_img" src="{{ product.miniphoto1 }}"></article>
								<article><img class="prod_img" src="{{ product.miniphoto2 }}"></article>
								<article><img class="prod_img" src="{{ product.miniphoto3 }}"></article>
								<article><img class="prod_img" src="{{ product.miniphoto4 }}"></article>

							</div>
						</div>
					</div>
					<div id="controls">
						<label for="switch1"></label>
						<label for="switch2"></label>
						<label for="switch3"></label>
						<label for="switch4"></label>
						<label for="switch5"></label>

					</div>
					<div id="active">
						<label for="switch1"></label>
						<label for="switch2"></label>
						<label for="switch3"></label>
						<label for="switch4"></label>
						<label for="switch5"></label>

					</div>
				</article>
			</div>
			<hr>	
				
			
				
				
			{% endif %}





			<h2 class="detail_name" >{{ product.name }}</h2>
			<h5 class="detail_deskription">{{ product.deskription }}</h5>

			<h5 class="detail_size">Доступные размеры: <br>{{ product.sizes }}</h5>
			<h5 class="detail_price">{{ product.price }} ₽</h5>

			<form id="form1" method="post">
				{% csrf_token %}
				<button id='submit_btn' class="btn btn-success detail_dropbutton"
						data-product-id ='{{ product.id }}'
						data-product-name="{{ product.name }}"
						data-product-img="{{ product.photo }}"
						data-product-price="{{ product.price }}"


				>
					Добавить в корзину</button>

				<br>
				<a id="order_btn" class="btn btn-success detail_order">Оформить заказ</a>
			</form>



		</div>
	</body>




{% endblock %}

public_html/main/templates/main/example.html
{% load static %}
<!doctype html>
<html lang="en" id="ord">
<header>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
    <script src="{% static '/main/js/head.js' %}"></script>
    

    <nav class="nav_head">

        <button id="menu_btn">
            <img id="menu_img" src="{% static '/main/img/menu_logo.svg'%}" alt="">
        </button>

        <div id="name_shop_div">
            <a class="name_shop" href="{% url 'main:home' %}"><ya-tr-span>BLYNSKY SHOP</ya-tr-span></a>
        </div>

        <div id="head_text_div">
            <button id="close_head_text"><img id="close_img" src="{% static '/main/img/close.svg' %}" alt=""></button>
            <a class="headtext" href="{% url 'main:home' %}"><img class="headtext_logo" src="{% static '/main/img/catalog_svg.svg'%}" alt=""> каталог</a>
            
            <hr class="hr_mobile">
            
            <a class="headtext" href="{% url 'main:about' %}"><img class="headtext_logo" src="{% static '/main/img/about_logo.svg'%}" alt=""> о нас </a>
            
            <hr class="hr_mobile">
            
            <!--<a class="headtext" href="{% url 'main:news' %}"><img class="headtext_logo" src="{% static '/main/img/new_icon.png'%}" alt=""> новости</a>-->
            
            <hr class="hr_mobile">
            
            <a class="headtext" href="{% url 'main:comments' %}"><img class="headtext_logo" src="{% static '/main/img/comment_logo.svg'%}" alt=""> отзывы</a>
            
            
            <hr class="hr_mobile">
            
        </div>

        <a class="butt" href="{% url 'main:basket' %}" ><img class="img_cart" src="{% static '/main/img/cart.svg'%}"></a>
    </nav>



</header>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

public_html/main/templates/main/mainpage.html
{% extends 'main/example.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'main/css/product_list.css' %}">
    <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.js"></script>
    <script src="{% static '/main/js/catalog.js' %}"></script>
    <title>Главная</title>
    <h1>{{title}}</h1>
    {% if search_query != None %}
        <h3> Результаты по запросу {{ search_query }} </h3>
    {% endif %}

    <link rel=”icon” href="{% static '/main/icons/blsh.ico' %}" type=”image/x-icon”>

    <head>
        <link rel="shortcut icon" href="{% static '/main/icons/blsh.ico' %}" type="image/x-icon">
    </head>
    
    


    <div id="main">

    
        <div id="left_block">

            <button id="close"><img id="close_img" src="{% static '/main/img/close.svg' %}" alt=""></button>
            <div id="scroll_elem">

                <div class="sort_filter_div">
                    <h2 id="sort_category_inf">Категории</h2>
                    
                    <button class="off_filter">все</button>
                    <br>
                    {% for elem in categories %}
                        <button class="category">{{ elem }}</button><br>
                    {% endfor %}
                </div>

                <div class="sort_filter_div">
                    <h2 id="sort_brand_inf">Бренды</h2>

                    <button class="off_filter">все</button>
                    <br>
                    {% for elem in brands %}
                        <button class="brand">{{ elem }}</button><br>
                    {% endfor %}
                    
                
                </div>
            </div>

        </div>


        <div id="center_block">
            <h2>Каталог</h2>

            <div id="search_div">
                <button id="filter_btn">
                    <img id="filter_img" src="{% static '/main/img/filter_logo.svg'%}" alt="">
                </button>
                <div id="div_sort_btn">
                    <button id="sort_btn">Сначала старые</button>
                    <img id="sort_btn_png" src="{% static '/main/img/sort.png'%}" alt="">
                    
                    
                    <div id="sort_div">
                        <button id="btn_sort_down" class="sort_indiv_btn">По возрастанию цены</button>
                        <br>
                        <button id="btn_sort_up" class="sort_indiv_btn">По убыванию цены</button>
                        <br>
                        <button id="btn_sort_new" class="sort_indiv_btn">Сначала новые</button>
                        <br>
                        <button id="btn_sort_alt" class="sort_indiv_btn">Сначала старые</button>
                        <br>
                     </div>
                     
                </div>

                <input id="elastic" type="search" class="catalog_search" placeholder="Я ищу.." name="search">
            </div>




            <div id="nav" class="list_product">
                
           
                
                {% for el in prod %}
                    <div class="prod_cart"
                         data-product-id="{{ el.id }}"
                         data-product-name="{{ el.name }}"
                         data-product-price="{{ el.price }}"
                         data-product-category="{{ el.category }}"
                         data-product-brand="{{ el.brand }}"
                    >

                        <a href="{% url 'main:newprod' el.id %}"><img class="prod_img" src="{{ el.photo.url }}" alt="f"></a>
                        <h5 class="prod_name">{{ el.name }}</h5>
                        <h5 class="prod_price">{{ el.price }} ₽</h5>
                        <h5 class="prod_size">Размеры в наличии: <br> {{ el.sizes }}</h5>

                    </div>
                {% endfor %}
            </div>
        </div>


    </div>


{% endblock %}

public_html/main/templates/main/new_view.html
{% extends 'main/example.html' %}
{% load static %}
{% block content %}
    <title>{{ new.header }}</title>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="{% static '/main/js/scripts.js' %}"></script>
	<link rel="stylesheet" href="{% static 'main/css/new_detail.css' %}">

    
	<body id="body">
        <h1 class='header'>{{ new.header }}</h1>
        
        <div class="new_text_div">
            {% if new.photo %}
                <img class="news_img" src="{{ new.photo.url }}" alt="f">
            {% endif %}
            <span class="new_text">{{ new.news_text }}</span>
        </div>
        
        
		
	</body>




{% endblock %}

public_html/main/templates/main/news.html
{% extends 'main/example.html' %}
{% load static %}
{% block content %}
    <title>Новости</title>
    <script src="{% static '/main/js/news.js' %}"></script>
    <link rel="stylesheet" href="{% static 'main/css/news.css' %}">
    
    <body id="body">
        <h1 id="h1_info">Новости</h1>
        <h5 id="h5_info">Тут вы можете узнать о новых поступлениях товаров, скидках и конкурсах.</h2>
        
        <div id="all_news_div">
            {% for new in news %}
            
                <div class="new_div">
                    {% if new.photo %}
                        <img class="news_img" src="{{ new.photo.url }}" alt="f">
                    {% else %}
                        <img class="news_img news_belt" src="{% static '/main/img/newss/belt2.png' %}" alt="f">
                    {% endif %}
                    
                    
               
                    <span class="new_header">{{ new.header }}</span>
                    
                  
                    
                    <a class="button_more" href="{% url 'main:newnew' new.id %}">Подробнее</a>
                    
                </div>
                
            {% endfor %}
            
        </div>
        
    </body>

{% endblock %}